"""Sphinx configuration for the ptiff Python bindings."""

from __future__ import annotations

import sys
from pathlib import Path

# -- Path setup --------------------------------------------------------------

# Add the package src directory so autodoc can import `ptiff` without installing.
SRC = Path(__file__).resolve().parents[1] / "src"
sys.path.insert(0, str(SRC))

# The Python bindings are promoted SWIG output (see the "alles in SWIG"
# migration notes in bindings/swig/README.md): `ptiff.py` + the compiled
# `_ptiff` C extension, both generated by `make -C ../swig python` against a
# built libptiff_c. Building the API reference therefore requires that build
# step to have run first (`_ptiff.so` must be importable) — the same
# prerequisite as the test suite.

# -- Project information -----------------------------------------------------

project = "ptiff"
copyright = "PTIFF contributors"
author = "PTIFF contributors"

release = "0.4.0"

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# -- Options for HTML output -------------------------------------------------

html_theme = "sphinx_rtd_theme"

# -- Options for autodoc / intersphinx --------------------------------------

autodoc_member_order = "bysource"
autodoc_typehints = "description"

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}
