function c = ptiff_constants_mex()
%PTIFF_CONSTANTS_MEX  PTIFF_* numeric constants for the ptiff-octave binding.
%
%   Returns a struct with 24 fields mirroring the SWIG enum constants
%   (which the platform tests compare against for feature parity). The MEX
%   binding does not register these as Octave globals; this helper makes them
%   available as plain numbers.
c = struct( ...
  'PTIFF_ERROR_NOT_IMPLEMENTED', 0, ...
  'PTIFF_ERROR_INVALID_ARGUMENT', 1, ...
  'PTIFF_ERROR_OUT_OF_RANGE', 2, ...
  'PTIFF_ERROR_NOT_FOUND', 3, ...
  'PTIFF_ERROR_UNKNOWN', 4, ...
  'PTIFF_LOG_TRACE', 0, ...
  'PTIFF_LOG_DEBUG', 1, ...
  'PTIFF_LOG_INFO', 2, ...
  'PTIFF_LOG_WARN', 3, ...
  'PTIFF_LOG_ERROR', 4, ...
  'PTIFF_LOG_CRITICAL', 5, ...
  'PTIFF_LOG_OFF', 6, ...
  'PTIFF_PIXEL_UINT8', 0, ...
  'PTIFF_PIXEL_UINT16', 1, ...
  'PTIFF_PIXEL_UINT32', 2, ...
  'PTIFF_PIXEL_FLOAT32', 3, ...
  'PTIFF_PIXEL_FLOAT64', 4, ...
  'PTIFF_COMPRESSION_NONE', 0, ...
  'PTIFF_COMPRESSION_LZW', 1, ...
  'PTIFF_COMPRESSION_DEFLATE', 2, ...
  'PTIFF_COMPRESSION_JPEG', 3, ...
  'PTIFF_ABI_VERSION', ptiff_abi_version());
end
