//! Idiomatic Rust bindings to libptiff via the language-agnostic C ABI
//! (`libptiff_c`, see `bindings/c`). This crate never links libptiff's C++ API
//! directly; it talks only to the stable `extern "C"` surface, exactly like the
//! Go, Python and Ruby bindings do.
//!
//! # Linking
//!
//! Point `PTIFF_C_LIB_DIR` at the directory containing `libptiff_c` (and
//! optionally `PTIFF_LIB_DIR` at the `libptiff` dir for the transitive shared
//! dependency), then:
//!
//! ```bash
//! PTIFF_C_LIB_DIR=/path/to/build/.../bindings/c \
//! PTIFF_LIB_DIR=/path/to/build/libptiff \
//! cargo test
//! ```

use std::ffi::{CStr, CString};
use std::os::raw::{c_double, c_int};
use std::path::Path;

// Raw `extern "C"` FFI declarations generated by `bindgen` directly from the
// C ABI headers under `bindings/c` (see `build.rs`). Never hand-edit this file
// or the manual-FFI duplication it replaces: the C headers are the single
// source of truth.
#[allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    clippy::all
)]
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/ptiff_ffi.rs"));
}

// C value structs / opaque handles re-exported from the generated bindings so
// the rest of this crate (and downstream consumers) use the same types as the
// FFI boundary -- there is no manual struct duplication to keep in sync.
pub use ffi::ptiff_field as Field;
pub use ffi::ptiff_version as Version;
pub use ffi::{ptiff_image as ImageHandle, ptiff_sink as SinkHandle, ptiff_source as SourceHandle};
pub use ffi::{ptiff_image_descriptor as ImageDescriptor, ptiff_tile_info as TileInfo};

// ---------------------------------------------------------------------------
// Idiomatic value types over the C ABI.
// ---------------------------------------------------------------------------

/// Error codes (matches `ptiff::ErrorCode`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum ErrorCode {
    NotImplemented = 0,
    InvalidArgument = 1,
    OutOfRange = 2,
    NotFound = 3,
    Unknown = 4,
}

impl ErrorCode {
    /// Human-friendly name, mirroring the C++ enum naming.
    pub fn as_str(&self) -> &'static str {
        match self {
            ErrorCode::NotImplemented => "not implemented",
            ErrorCode::InvalidArgument => "invalid argument",
            ErrorCode::OutOfRange => "out of range",
            ErrorCode::NotFound => "not found",
            ErrorCode::Unknown => "unknown",
        }
    }
}

/// Log levels (matches `ptiff::LogLevel`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum LogLevel {
    Trace = 0,
    Debug = 1,
    Info = 2,
    Warn = 3,
    Error = 4,
    Critical = 5,
    Off = 6,
}

/// Pixel types (matches `ptiff::PixelType`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum PixelType {
    UInt8 = 0,
    UInt16 = 1,
    UInt32 = 2,
    Float32 = 3,
    Float64 = 4,
}

impl PixelType {
    /// Stable, human-friendly name (e.g. `"UInt16"`), matching
    /// `ptiff::PixelType`'s enumerator spelling used by the bindings.
    pub fn name(&self) -> &'static str {
        match self {
            PixelType::UInt8 => "UInt8",
            PixelType::UInt16 => "UInt16",
            PixelType::UInt32 => "UInt32",
            PixelType::Float32 => "Float32",
            PixelType::Float64 => "Float64",
        }
    }
}

/// Compression kinds (matches `ptiff::CompressionKind`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum CompressionKind {
    None = 0,
    Lzw = 1,
    Deflate = 2,
    Jpeg = 3,
}

// ---------------------------------------------------------------------------
// Idiomatic API
// ---------------------------------------------------------------------------

/// Runtime version of the linked libptiff.
pub fn runtime_version() -> Version {
    unsafe { ffi::ptiff_runtime_version() }
}

/// Version libptiff's headers were compiled against.
pub fn compile_time_version() -> Version {
    unsafe { ffi::ptiff_compile_time_version() }
}

impl std::fmt::Display for Version {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}.{}.{}", self.major, self.minor, self.patch)
    }
}

/// Comma-space-separated list of registered backend names.
pub fn backend_names() -> Vec<String> {
    unsafe {
        let raw = ffi::ptiff_backend_names();
        if raw.is_null() {
            return Vec::new();
        }
        let s = CStr::from_ptr(raw).to_string_lossy().into_owned();
        // The C shim allocates with malloc; we must free it symmetrically.
        ffi::ptiff_free_string(raw);
        s.split(", ").map(|x| x.to_string()).collect()
    }
}

/// The process-wide logger singleton handle.
pub struct Logger;

impl Logger {
    /// Returns the shared logger instance.
    pub fn instance() -> Logger {
        Logger
    }

    pub fn set_level(&self, level: LogLevel) {
        unsafe { ffi::ptiff_logger_set_level(level as c_int) }
    }

    pub fn level(&self) -> LogLevel {
        unsafe { std::mem::transmute::<c_int, LogLevel>(ffi::ptiff_logger_level()) }
    }

    pub fn log(&self, level: LogLevel, message: &str) {
        let msg = CString::new(message).unwrap_or_default();
        unsafe { ffi::ptiff_logger_log(level as c_int, msg.as_ptr()) }
    }

    pub fn trace(&self, m: &str) {
        self.log(LogLevel::Trace, m)
    }
    pub fn debug(&self, m: &str) {
        self.log(LogLevel::Debug, m)
    }
    pub fn info(&self, m: &str) {
        self.log(LogLevel::Info, m)
    }
    pub fn warn(&self, m: &str) {
        self.log(LogLevel::Warn, m)
    }
    pub fn error(&self, m: &str) {
        self.log(LogLevel::Error, m)
    }
    pub fn critical(&self, m: &str) {
        self.log(LogLevel::Critical, m)
    }
}

/// A convenience builder for `ImageDescriptor`.
#[derive(Debug, Clone, Copy)]
pub struct ImageDescriptorBuilder {
    pub width: u32,
    pub height: u32,
    pub pixel_type: PixelType,
    pub channel_count: u32,
    pub gsd: Option<f64>,
    pub tile_info: Option<TileInfo>,
    pub compression: Option<CompressionKind>,
}

impl ImageDescriptorBuilder {
    pub fn new(width: u32, height: u32, pixel_type: PixelType) -> Self {
        Self {
            width,
            height,
            pixel_type,
            channel_count: 1,
            gsd: None,
            tile_info: None,
            compression: None,
        }
    }

    pub fn channel_count(mut self, n: u32) -> Self {
        self.channel_count = n;
        self
    }
    pub fn gsd(mut self, m: f64) -> Self {
        self.gsd = Some(m);
        self
    }
    pub fn tile(mut self, w: u32, h: u32) -> Self {
        self.tile_info = Some(TileInfo {
            tile_width: w,
            tile_height: h,
        });
        self
    }
    pub fn compression(mut self, k: CompressionKind) -> Self {
        self.compression = Some(k);
        self
    }

    fn to_ffi(self) -> ImageDescriptor {
        ImageDescriptor {
            width: self.width,
            height: self.height,
            pixel_type: self.pixel_type as c_int,
            channel_count: self.channel_count,
            has_gsd: self.gsd.is_some() as c_int,
            gsd: self.gsd.unwrap_or(0.0),
            has_tile_info: self.tile_info.is_some() as c_int,
            tile_info: self.tile_info.unwrap_or_default(),
            has_compression: self.compression.is_some() as c_int,
            compression: self.compression.map(|k| k as c_int).unwrap_or(0),
        }
    }

    pub fn build(self) -> Image {
        let desc = self.to_ffi();
        unsafe {
            let raw = ffi::ptiff_image_create(&desc);
            if raw.is_null() {
                panic!("ptiff_image_create failed");
            }
            Image { raw }
        }
    }
}

/// RAII wrapper around a heap-owned `ptiff::Image`.
pub struct Image {
    raw: *mut ImageHandle,
}

impl Drop for Image {
    fn drop(&mut self) {
        unsafe { ffi::ptiff_image_destroy(self.raw) }
    }
}

impl Image {
    pub fn width(&self) -> u32 {
        unsafe { ffi::ptiff_image_width(self.raw) }
    }
    pub fn height(&self) -> u32 {
        unsafe { ffi::ptiff_image_height(self.raw) }
    }
    pub fn pixel_type(&self) -> PixelType {
        unsafe { std::mem::transmute::<c_int, PixelType>(ffi::ptiff_image_pixel_type(self.raw)) }
    }
    pub fn channel_count(&self) -> u32 {
        unsafe { ffi::ptiff_image_channel_count(self.raw) }
    }

    pub fn gsd(&self) -> Option<f64> {
        unsafe {
            let mut out: c_double = 0.0;
            if ffi::ptiff_image_gsd(self.raw, &mut out) != 0 {
                Some(out)
            } else {
                None
            }
        }
    }

    pub fn tile_info(&self) -> Option<TileInfo> {
        unsafe {
            let mut out: TileInfo = TileInfo::default();
            if ffi::ptiff_image_tile_info(self.raw, &mut out) != 0 {
                Some(out)
            } else {
                None
            }
        }
    }

    pub fn compression(&self) -> Option<CompressionKind> {
        unsafe {
            let mut out: c_int = 0;
            if ffi::ptiff_image_compression(self.raw, &mut out) != 0 {
                Some(std::mem::transmute::<c_int, CompressionKind>(out))
            } else {
                None
            }
        }
    }
}

/// Metadata read from an on-disk TIFF/BigTIFF file via `ptiff_open_path`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct FileMetadata {
    pub width: u32,
    pub height: u32,
    pub pixel_type: PixelType,
    pub channel_count: u32,
    /// Present when the file declares a tile size.
    pub tile_info: Option<TileInfo>,
}

/// An error opening/reading a path. The raw value is the negative C ABI error
/// code (see `bindings/c` `ptiff_error_code`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpenError(pub i32);

impl OpenError {
    /// Human-friendly description, mirroring `ptiff::ErrorCode`.
    pub fn as_str(self) -> &'static str {
        match -self.0 {
            0 => "not implemented",
            1 => "invalid argument",
            2 => "out of range",
            3 => "not found",
            _ => "unknown",
        }
    }
}

impl std::fmt::Display for OpenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{} (code {})", self.as_str(), self.0)
    }
}

impl std::error::Error for OpenError {}

/// Opens a TIFF/BigTIFF file with the C ABI's `ptiff_open_path` and returns
/// its primary image metadata.
///
/// # Errors
///
/// Returns the C ABI's negative `ptiff_*` error code wrapped in [`OpenError`]
/// when the file cannot be opened or read (e.g. `Error::NotFound`).
pub fn open_path(path: impl AsRef<Path>) -> Result<FileMetadata, OpenError> {
    let path_str = path
        .as_ref()
        .to_str()
        .ok_or(OpenError(-(ErrorCode::InvalidArgument as i32)))?;
    let c_path =
        CString::new(path_str).map_err(|_| OpenError(-(ErrorCode::InvalidArgument as i32)))?;

    let mut desc = ImageDescriptor {
        width: 0,
        height: 0,
        pixel_type: 0,
        channel_count: 0,
        has_gsd: 0,
        gsd: 0.0,
        has_tile_info: 0,
        tile_info: TileInfo::default(),
        has_compression: 0,
        compression: 0,
    };

    let rc = unsafe { ffi::ptiff_open_path(c_path.as_ptr(), &mut desc) };
    if rc != 0 {
        return Err(OpenError(rc));
    }

    Ok(FileMetadata {
        width: desc.width,
        height: desc.height,
        pixel_type: unsafe { std::mem::transmute::<c_int, PixelType>(desc.pixel_type) },
        channel_count: desc.channel_count,
        tile_info: if desc.has_tile_info != 0 {
            Some(desc.tile_info)
        } else {
            None
        },
    })
}

/// Opens a TIFF/BigTIFF file via the C ABI's `ptiff_open_path_fields` and
/// returns its flattened PTIFF extension fields decoded from the private tags
/// 65001-65005 (SPICE, camera geometry, CRS, scientific layers, provenance).
///
/// Keys carry the `ptiff.<domain>.<name>` shape (e.g. `"ptiff.spice.frame"`)
/// and the resulting vector is ordered lexicographically by key. Each element
/// is an owned `(key, value)` pair; the underlying C array is freed
/// automatically with `ptiff_fields_free`.
///
/// # Errors
///
/// Returns the C ABI's negative `ptiff_*` error code wrapped in [`OpenError`]
/// when the file cannot be opened or read (e.g. `Error::NotFound`).
pub fn open_path_fields(path: impl AsRef<Path>) -> Result<Vec<(String, String)>, OpenError> {
    let path_str = path
        .as_ref()
        .to_str()
        .ok_or(OpenError(-(ErrorCode::InvalidArgument as i32)))?;
    let c_path =
        CString::new(path_str).map_err(|_| OpenError(-(ErrorCode::InvalidArgument as i32)))?;

    let mut out: *mut Field = std::ptr::null_mut();
    let mut out_count: c_int = 0;

    let rc = unsafe { ffi::ptiff_open_path_fields(c_path.as_ptr(), &mut out, &mut out_count) };
    if rc != 0 {
        return Err(OpenError(rc));
    }

    let count = out_count as usize;
    let mut fields = Vec::with_capacity(count);
    if !out.is_null() {
        for i in 0..count {
            let f = unsafe { &*out.add(i) };
            let key = unsafe { CStr::from_ptr(f.key) }
                .to_string_lossy()
                .into_owned();
            let value = unsafe { CStr::from_ptr(f.value) }
                .to_string_lossy()
                .into_owned();
            fields.push((key, value));
        }
    }
    unsafe { ffi::ptiff_fields_free(out, out_count) };
    Ok(fields)
}

/// Structured camera calibration decoded from the `ptiff.camera.*` extension
/// fields of a TIFF/BigTIFF file. Carries the pinhole intrinsics, the
/// extrinsics (rotation quaternion + world translation), the ISO-8601
/// observation timestamp, and the three derived matrices K / [R|t] / P (all
/// row-major doubles). The projection `P = K * [R|t]` is computed in the C++
/// library.
#[derive(Debug, Clone)]
pub struct Camera {
    pub has_intrinsics: bool,
    pub focal_length_x: f64,
    pub focal_length_y: f64,
    pub principal_x: f64,
    pub principal_y: f64,
    /// 3x3 intrinsic calibration matrix K (row-major).
    pub intrinsics: [f64; 9],
    pub has_extrinsics: bool,
    pub rotation_w: f64,
    pub rotation_x: f64,
    pub rotation_y: f64,
    pub rotation_z: f64,
    pub position_x: f64,
    pub position_y: f64,
    pub position_z: f64,
    /// 3x4 extrinsic matrix [R | t] (row-major).
    pub extrinsics: [f64; 12],
    /// 3x4 projection matrix P = K * [R | t] (row-major).
    pub projection: [f64; 12],
    /// ISO-8601 UTC observation timestamp; empty when unset.
    pub timestamp: String,
    /// The camera model name, e.g. `"pinhole"`. Read from the
    /// `ptiff.camera.model` extension field when available; defaults to
    /// `"pinhole"` when constructing a [`Camera::pinhole`].
    pub model: String,
}

impl Camera {
    /// Constructs a camera calibration suitable for **writing** to a new file
    /// via [`Sink::create_with_camera`] from raw pinhole intrinsics and
    /// extrinsics. `timestamp` defaults to empty when `None`.
    ///
    /// Only the scalar fields (`focal_length_*`, `principal_*`,
    /// `rotation_*`, `position_*`) are persisted into the
    /// `ptiff.camera.*` metadata; the derived matrices `K`, `[R | t]` and
    /// `P = K * [R | t]` are computed by the C++ library on read and are left
    /// zero-filled here.
    #[allow(clippy::too_many_arguments)]
    pub fn pinhole(
        focal_length_x: f64,
        focal_length_y: f64,
        principal_x: f64,
        principal_y: f64,
        rotation_w: f64,
        rotation_x: f64,
        rotation_y: f64,
        rotation_z: f64,
        position_x: f64,
        position_y: f64,
        position_z: f64,
        timestamp: Option<String>,
    ) -> Camera {
        Camera {
            has_intrinsics: true,
            focal_length_x,
            focal_length_y,
            principal_x,
            principal_y,
            intrinsics: [0.0; 9],
            has_extrinsics: true,
            rotation_w,
            rotation_x,
            rotation_y,
            rotation_z,
            position_x,
            position_y,
            position_z,
            extrinsics: [0.0; 12],
            projection: [0.0; 12],
            timestamp: timestamp.unwrap_or_default(),
            model: "pinhole".to_string(),
        }
    }

    /// Converts this calibration into the C ABI `ptiff_camera` struct used by
    /// `ptiff_sink_create_camera` for writing.
    fn to_ffi(&self) -> ffi::ptiff_camera {
        let mut timestamp = [0i8; 64];
        let bytes = self.timestamp.as_bytes();
        let n = bytes.len().min(63);
        for (i, b) in bytes[..n].iter().enumerate() {
            timestamp[i] = *b as i8;
        }
        ffi::ptiff_camera {
            has_intrinsics: self.has_intrinsics as i32,
            focal_length_x: self.focal_length_x,
            focal_length_y: self.focal_length_y,
            principal_x: self.principal_x,
            principal_y: self.principal_y,
            intrinsics: [0.0; 9],
            has_extrinsics: self.has_extrinsics as i32,
            rotation_w: self.rotation_w,
            rotation_x: self.rotation_x,
            rotation_y: self.rotation_y,
            rotation_z: self.rotation_z,
            position_x: self.position_x,
            position_y: self.position_y,
            position_z: self.position_z,
            extrinsics: [0.0; 12],
            projection: [0.0; 12],
            timestamp,
        }
    }
}

/// Opens a TIFF/BigTIFF file at `path` and returns the structured camera
/// calibration decoded from its `ptiff.camera.*` extension fields (see
/// [`Camera`]).
///
/// # Errors
///
/// Returns the C ABI's negative `ptiff_*` error code wrapped in [`OpenError`]
/// when the file cannot be opened or read.
pub fn open_path_camera(path: impl AsRef<Path>) -> Result<Camera, OpenError> {
    let path_str = path
        .as_ref()
        .to_str()
        .ok_or(OpenError(-(ErrorCode::InvalidArgument as i32)))?;
    let c_path =
        CString::new(path_str).map_err(|_| OpenError(-(ErrorCode::InvalidArgument as i32)))?;

    let mut cam = ffi::ptiff_camera {
        has_intrinsics: 0,
        focal_length_x: 0.0,
        focal_length_y: 0.0,
        principal_x: 0.0,
        principal_y: 0.0,
        intrinsics: [0.0; 9],
        has_extrinsics: 0,
        rotation_w: 0.0,
        rotation_x: 0.0,
        rotation_y: 0.0,
        rotation_z: 0.0,
        position_x: 0.0,
        position_y: 0.0,
        position_z: 0.0,
        extrinsics: [0.0; 12],
        projection: [0.0; 12],
        timestamp: [0; 64],
    };

    let rc = unsafe { ffi::ptiff_open_path_camera(c_path.as_ptr(), &mut cam) };
    if rc != 0 {
        return Err(OpenError(rc));
    }

    let c_str = unsafe { CStr::from_ptr(cam.timestamp.as_ptr()) };

    // The C ABI struct has no camera-model slot; recover it from the
    // `ptiff.camera.model` extension field where present (default "pinhole").
    let model = open_path_fields(path)
        .ok()
        .and_then(|fields| {
            fields
                .iter()
                .find(|(k, _)| k == "ptiff.camera.model")
                .map(|(_, v)| v.clone())
        })
        .unwrap_or_else(|| "pinhole".to_string());

    Ok(Camera {
        has_intrinsics: cam.has_intrinsics != 0,
        focal_length_x: cam.focal_length_x,
        focal_length_y: cam.focal_length_y,
        principal_x: cam.principal_x,
        principal_y: cam.principal_y,
        intrinsics: cam.intrinsics,
        has_extrinsics: cam.has_extrinsics != 0,
        rotation_w: cam.rotation_w,
        rotation_x: cam.rotation_x,
        rotation_y: cam.rotation_y,
        rotation_z: cam.rotation_z,
        position_x: cam.position_x,
        position_y: cam.position_y,
        position_z: cam.position_z,
        extrinsics: cam.extrinsics,
        projection: cam.projection,
        timestamp: c_str.to_string_lossy().into_owned(),
        model,
    })
}

/// Full read-side metadata for an on-disk TIFF/BigTIFF file: the primary
/// image descriptor, the flattened PTIFF extension fields, and the structured
/// camera calibration (when present). A single [`read_metadata`] call returns
/// everything the idiomatic layer knows about a file in one go.
#[derive(Debug, Clone)]
pub struct Metadata {
    /// Primary image descriptor (width, height, pixel type, channels, tiles).
    pub file: FileMetadata,
    /// Flattened PTIFF extension fields as `(key, value)` pairs (keys carry
    /// the `ptiff.<domain>.<name>` shape), ordered lexicographically.
    pub fields: Vec<(String, String)>,
    /// Structured camera calibration; `None` when the file has neither
    /// intrinsics nor extrinsics.
    pub camera: Option<Camera>,
}

impl Metadata {
    /// Looks up a single flattened extension field by its fully qualified key
    /// (e.g. `"ptiff.spice.frame"`), returning `None` when absent. Mirrors the
    /// `field(key)` accessor of the Python binding.
    pub fn field(&self, key: &str) -> Option<&str> {
        self.fields
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, v)| v.as_str())
    }
}

/// Reads the complete read-side metadata of the TIFF/BigTIFF file at `path` in
/// a single call: [`FileMetadata`], the flattened `ptiff.<domain>.<name>`
/// extension fields, and the structured [`Camera`] (when present). This is the
/// one-stop "inspect a file" entry point, uniform with the `read_metadata`
/// tool of the MCP binding.
///
/// # Errors
///
/// Returns the C ABI's negative `ptiff_*` error code wrapped in [`OpenError`]
/// when the file cannot be opened or read.
pub fn read_metadata(path: impl AsRef<Path>) -> Result<Metadata, OpenError> {
    let file = open_path(&path)?;
    let fields = open_path_fields(&path)?;
    let camera = open_path_camera(&path)
        .ok()
        .filter(|c| c.has_intrinsics || c.has_extrinsics);
    Ok(Metadata {
        file,
        fields,
        camera,
    })
}

/// An error creating or writing with a [`Sink`]. The raw value is the negative
/// C ABI error code (see `bindings/c` `ptiff_error_code`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WriteError(pub i32);

impl WriteError {
    /// Human-friendly description, mirroring `ptiff::ErrorCode`.
    pub fn as_str(self) -> &'static str {
        match -self.0 {
            0 => "not implemented",
            1 => "invalid argument",
            2 => "out of range",
            3 => "not found",
            _ => "unknown",
        }
    }
}

impl std::fmt::Display for WriteError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{} (code {})", self.as_str(), self.0)
    }
}

impl std::error::Error for WriteError {}

/// Error creating a [`Sink`]. The C ABI's `ptiff_sink_create` returns NULL on
/// failure without exposing an error code, so we surface a generic
/// `ErrorCode::Unknown`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CreateError;

impl std::fmt::Display for CreateError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "ptiff_sink_create failed")
    }
}

impl std::error::Error for CreateError {}

/// RAII wrapper around a heap-owned write-side `ptiff::Sink` (see
/// `bindings/c/ptiff_pixel_bridge.h`). Dropping it flushes the underlying
/// writer via `ptiff_sink_close`.
///
/// The image must be tiled (`has_tile_info` set), otherwise the C ABI rejects
/// the descriptor — use [`ImageDescriptorBuilder::tile`].
pub struct Sink {
    raw: *mut SinkHandle,
}

impl Drop for Sink {
    fn drop(&mut self) {
        unsafe { ffi::ptiff_sink_close(self.raw) }
    }
}

impl Sink {
    /// Creates a TIFF/BigTIFF file at `path` for writing a single tiled image
    /// described by `builder`. `builder` **must** have `tile` set (a tiled
    /// layout is required for TIFF tile I/O).
    ///
    /// # Errors
    ///
    /// Returns [`CreateError`] if the C ABI could not create the sink (e.g. a
    /// non-tiled or otherwise invalid descriptor).
    pub fn create(
        path: impl AsRef<Path>,
        builder: ImageDescriptorBuilder,
    ) -> Result<Sink, CreateError> {
        let path_str = path.as_ref().to_str().ok_or(CreateError)?;
        let c_path = CString::new(path_str).map_err(|_| CreateError)?;

        let desc = builder.to_ffi();
        let raw = unsafe { ffi::ptiff_sink_create(c_path.as_ptr(), &desc) };
        if raw.is_null() {
            return Err(CreateError);
        }
        Ok(Sink { raw })
    }

    /// Creates a TIFF/BigTIFF file at `path` for writing a single tiled image
    /// described by `builder`, persisting `camera`'s calibration as
    /// `ptiff.camera.*` metadata (see [`Camera::pinhole`]). `builder`
    /// **must** have `tile` set.
    ///
    /// # Errors
    ///
    /// Returns [`CreateError`] if the C ABI could not create the sink (e.g. a
    /// NULL camera or an invalid descriptor).
    pub fn create_with_camera(
        path: impl AsRef<Path>,
        builder: ImageDescriptorBuilder,
        camera: &Camera,
    ) -> Result<Sink, CreateError> {
        let path_str = path.as_ref().to_str().ok_or(CreateError)?;
        let c_path = CString::new(path_str).map_err(|_| CreateError)?;

        let desc = builder.to_ffi();
        let cam = camera.to_ffi();
        let raw = unsafe { ffi::ptiff_sink_create_camera(c_path.as_ptr(), &desc, &cam) };
        if raw.is_null() {
            return Err(CreateError);
        }
        Ok(Sink { raw })
    }

    /// Tile grid columns at level 0.
    pub fn tile_columns(&self) -> u32 {
        unsafe { ffi::ptiff_sink_tile_columns(self.raw) }
    }

    /// Tile grid rows at level 0.
    pub fn tile_rows(&self) -> u32 {
        unsafe { ffi::ptiff_sink_tile_rows(self.raw) }
    }

    /// Byte size of one written tile's pixel data. Edge tiles are TIFF-padded
    /// to this uniform size.
    pub fn tile_byte_size(&self) -> usize {
        unsafe { ffi::ptiff_sink_tile_byte_size(self.raw) }
    }

    /// Writes one tile of raw, uncompressed pixel data to grid cell
    /// (`column`, `row`). `buffer` must be exactly `self.tile_byte_size()`
    /// bytes (the C ABI returns `InvalidArgument` on a mismatch).
    ///
    /// # Errors
    ///
    /// Returns a [`WriteError`] carrying the negative C ABI error code (e.g.
    /// `OutOfRange` for an out-of-grid tile index, or `InvalidArgument` for a
    /// buffer size mismatch).
    pub fn write_tile(&self, column: u32, row: u32, buffer: &[u8]) -> Result<(), WriteError> {
        let rc = unsafe {
            ffi::ptiff_sink_write_tile(self.raw, column, row, buffer.as_ptr(), buffer.len())
        };
        if rc != 0 {
            return Err(WriteError(rc));
        }
        Ok(())
    }
}

/// An error opening or reading a [`Source`]. The raw value is the negative C
/// ABI error code (see `bindings/c` `ptiff_error_code`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReadError(pub i32);

impl ReadError {
    /// Human-friendly description, mirroring `ptiff::ErrorCode`.
    pub fn as_str(self) -> &'static str {
        match -self.0 {
            0 => "not implemented",
            1 => "invalid argument",
            2 => "out of range",
            3 => "not found",
            _ => "unknown",
        }
    }
}

impl std::fmt::Display for ReadError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{} (code {})", self.as_str(), self.0)
    }
}

impl std::error::Error for ReadError {}

/// RAII wrapper around a heap-owned read-side `ptiff::Source` (see
/// `bindings/c/ptiff_pixel_bridge.h`). Dropping it releases the underlying
/// reader via `ptiff_source_close`.
///
/// A source is a live handle over an open TIFF/BigTIFF file's primary image,
/// ready for tile/strip reads — the pixel-read counterpart of [`Sink`]. Both
/// tiled and striped images are exposed as a uniform tile grid via
/// [`Source::tile_columns`]/[`Source::tile_rows`].
pub struct Source {
    raw: *mut SourceHandle,
}

impl Drop for Source {
    fn drop(&mut self) {
        unsafe { ffi::ptiff_source_close(self.raw) }
    }
}

impl Source {
    /// Opens the primary image in the TIFF/BigTIFF file at `path` for pixel
    /// reading.
    ///
    /// # Errors
    ///
    /// Returns [`ReadError`] when the file cannot be opened or is not a valid
    /// TIFF/BigTIFF.
    pub fn open(path: impl AsRef<Path>) -> Result<Source, ReadError> {
        let path_str = path
            .as_ref()
            .to_str()
            .ok_or(ReadError(-(ErrorCode::InvalidArgument as i32)))?;
        let c_path =
            CString::new(path_str).map_err(|_| ReadError(-(ErrorCode::InvalidArgument as i32)))?;

        let mut err: c_int = 0;
        let raw = unsafe { ffi::ptiff_source_open(c_path.as_ptr(), &mut err) };
        if raw.is_null() {
            return Err(ReadError(if err != 0 { err } else { -1 }));
        }
        Ok(Source { raw })
    }

    /// Fills an [`ImageDescriptor`] with the opened image's metadata (same
    /// fields `ptiff_open_path` fills).
    ///
    /// # Errors
    ///
    /// Returns a [`ReadError`] for a NULL source/descriptor.
    pub fn descriptor(&self) -> Result<ImageDescriptor, ReadError> {
        let mut desc = ImageDescriptor {
            width: 0,
            height: 0,
            pixel_type: 0,
            channel_count: 0,
            has_gsd: 0,
            gsd: 0.0,
            has_tile_info: 0,
            tile_info: TileInfo::default(),
            has_compression: 0,
            compression: 0,
        };
        let rc = unsafe { ffi::ptiff_source_descriptor(self.raw, &mut desc) };
        if rc != 0 {
            return Err(ReadError(rc));
        }
        Ok(desc)
    }

    /// Converts the source's descriptor into an [`ImageDescriptorBuilder`] so
    /// the same layout can be recreated, e.g. for a [`Sink`] write side.
    /// GSD/compression are best-effort (the read ABI does not surface them).
    pub fn descriptor_builder(&self) -> Result<ImageDescriptorBuilder, ReadError> {
        let desc = self.descriptor()?;
        let mut b = ImageDescriptorBuilder::new(desc.width, desc.height, unsafe {
            std::mem::transmute::<c_int, PixelType>(desc.pixel_type)
        })
        .channel_count(desc.channel_count);
        if desc.has_tile_info != 0 {
            b = b.tile(desc.tile_info.tile_width, desc.tile_info.tile_height);
        }
        Ok(b)
    }

    /// Tile grid columns at level 0. For a non-tiled image this is the strip
    /// count (a single strip → 1).
    pub fn tile_columns(&self) -> u32 {
        unsafe { ffi::ptiff_source_tile_columns(self.raw) }
    }

    /// Tile grid rows at level 0.
    pub fn tile_rows(&self) -> u32 {
        unsafe { ffi::ptiff_source_tile_rows(self.raw) }
    }

    /// Byte size of one decoded tile's pixel data (edge/strip tiles are
    /// TIFF-padded to this uniform size).
    pub fn tile_byte_size(&self) -> usize {
        unsafe { ffi::ptiff_source_tile_byte_size(self.raw) }
    }

    /// Reads one decoded tile/strip at grid cell (`column`, `row`) into
    /// `buffer`. `buffer` must be at least [`Source::tile_byte_size`] bytes.
    ///
    /// # Errors
    ///
    /// Returns a [`ReadError`] carrying the negative C ABI error code (e.g.
    /// `OutOfRange` for an out-of-grid index, or `InvalidArgument` for a too
    /// small buffer).
    pub fn read_tile(&self, column: u32, row: u32, buffer: &mut [u8]) -> Result<usize, ReadError> {
        let mut bytes_read: usize = 0;
        let rc = unsafe {
            ffi::ptiff_source_read_tile(
                self.raw,
                column,
                row,
                buffer.as_mut_ptr(),
                buffer.len(),
                &mut bytes_read,
            )
        };
        if rc != 0 {
            return Err(ReadError(rc));
        }
        Ok(bytes_read)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_roundtrip() {
        let v = runtime_version();
        assert_eq!(v.major, 0);
        eprintln!("runtime version: {v}");
    }

    #[test]
    fn runtime_matches_compile_time() {
        assert_eq!(runtime_version(), compile_time_version());
    }

    #[test]
    fn backends_registered() {
        let names = backend_names();
        assert!(!names.is_empty(), "expected backends, got {names:?}");
        eprintln!("backends: {names:?}");
    }

    #[test]
    fn logger_roundtrip() {
        let l = Logger::instance();
        l.set_level(LogLevel::Debug);
        assert_eq!(l.level(), LogLevel::Debug);
        l.set_level(LogLevel::Info);
        assert_eq!(l.level(), LogLevel::Info);
    }

    #[test]
    fn image_roundtrip() {
        let img = ImageDescriptorBuilder::new(10, 20, PixelType::UInt16)
            .gsd(0.5)
            .tile(16, 16)
            .compression(CompressionKind::Deflate)
            .channel_count(3)
            .build();
        assert_eq!(img.width(), 10);
        assert_eq!(img.height(), 20);
        assert_eq!(img.pixel_type(), PixelType::UInt16);
        assert_eq!(img.channel_count(), 3);
        assert_eq!(img.gsd(), Some(0.5));
        assert_eq!(
            img.tile_info(),
            Some(TileInfo {
                tile_width: 16,
                tile_height: 16
            })
        );
        assert_eq!(img.compression(), Some(CompressionKind::Deflate));
    }

    #[test]
    fn image_optionals_absent() {
        let img = ImageDescriptorBuilder::new(4, 4, PixelType::Float32).build();
        assert_eq!(img.gsd(), None);
        assert_eq!(img.tile_info(), None);
        assert_eq!(img.compression(), None);
    }

    /// A unique, per-invocation path in the OS temp dir for sink tests.
    fn temp_tiff(name: &str) -> std::path::PathBuf {
        let uniq = format!("ptiff_sink_{}_{name}.tif", std::process::id());
        std::env::temp_dir().join(uniq)
    }

    #[test]
    fn sink_writes_tiled_image() {
        let path = temp_tiff("write");
        // A 64x32 image tiled 32x16 -> 2x2 = 4 tiles. UInt8, 1 channel means
        // tile_byte_size == 32*16*1 == 512.
        let builder = ImageDescriptorBuilder::new(64, 32, PixelType::UInt8).tile(32, 16);

        let sink = Sink::create(&path, builder).expect("create sink");
        assert_eq!(sink.tile_columns(), 2);
        assert_eq!(sink.tile_rows(), 2);
        assert_eq!(sink.tile_byte_size(), 32 * 16);

        let tile: Vec<u8> = vec![0u8; 32 * 16];
        for c in 0..2 {
            for r in 0..2 {
                sink.write_tile(c, r, &tile).expect("write tile");
            }
        }

        drop(sink); // close (flush) the writer.

        // The file must now exist on disk (the sink wrote header+IFD at create
        // time and flushed the tiles on close).
        assert!(path.exists(), "expected written file {}", path.display());
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn sink_create_requires_tiled_descriptor() {
        // A non-tiled descriptor must be rejected by the C sink.
        let path = temp_tiff("no_tile");
        let builder = ImageDescriptorBuilder::new(64, 32, PixelType::UInt8);
        assert!(Sink::create(&path, builder).is_err());
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn sink_write_tile_validates_buffer_and_bounds() {
        let path = temp_tiff("validate");
        let builder = ImageDescriptorBuilder::new(64, 32, PixelType::UInt8).tile(32, 16);

        let sink = Sink::create(&path, builder).expect("create sink");
        let tile = vec![0u8; 32 * 16];

        // Wrong buffer size -> InvalidArgument (code -1).
        let too_short = vec![0u8; 32 * 16 - 1];
        assert_eq!(sink.write_tile(0, 0, &too_short), Err(WriteError(-1)));
        let too_long = vec![0u8; 32 * 16 + 1];
        assert_eq!(sink.write_tile(0, 0, &too_long), Err(WriteError(-1)));

        // Correct buffer, out-of-grid index -> OutOfRange (code -2).
        assert_eq!(sink.write_tile(5, 5, &tile), Err(WriteError(-2)));

        // A valid write still succeeds.
        sink.write_tile(1, 1, &tile).expect("write tile at (1,1)");

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn sink_close_is_idempotent() {
        // Writing through two successive Sink lifetimes on the same path proves
        // that close (via Drop) safely releases the underlying handle each time
        // and that a subsequent sink can take over the path.
        let path = temp_tiff("idempotent");

        {
            let builder = ImageDescriptorBuilder::new(32, 32, PixelType::UInt16).tile(16, 16);
            let sink = Sink::create(&path, builder).expect("create sink #1");
            let tile = vec![0u8; sink.tile_byte_size()];
            sink.write_tile(0, 0, &tile).expect("write #1");
            // dropped here -> ptiff_sink_close
        }

        {
            let builder = ImageDescriptorBuilder::new(32, 32, PixelType::UInt16).tile(16, 16);
            let sink = Sink::create(&path, builder).expect("create sink #2");
            sink.write_tile(1, 1, &vec![0u8; sink.tile_byte_size()])
                .expect("write #2");
        }

        assert!(path.exists(), "expected written file {}", path.display());
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn open_path_fields_reads_plain_tiff() {
        // Write a tiled TIFF via the sink (no `ptiff.*` fields), then read its
        // extension fields back through the new C ABI surface. A plain file has
        // no private-tag payloads, so the field vector must be empty — this
        // proves the FFI round-trips cleanly and the empty case is handled.
        let path = temp_tiff("fields");
        let builder = ImageDescriptorBuilder::new(16, 16, PixelType::UInt8).tile(16, 16);
        let sink = Sink::create(&path, builder).expect("create sink");
        sink.write_tile(0, 0, &vec![0u8; sink.tile_byte_size()])
            .expect("write tile");
        drop(sink);

        let fields = open_path_fields(&path).expect("open_path_fields");
        assert!(
            fields.is_empty(),
            "expected no ptiff fields, got {fields:?}"
        );

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn open_path_fields_reads_ptiff_camera_metadata_fixture() {
        // Read the real interop fixture (see scripts/samples) and assert the
        // `ptiff.camera.*` extension fields surface through the C ABI. This
        // keeps the idiomatic Rust surface honest against the same on-disk
        // format the Go/Python/Ruby/Octave bindings consume.
        let fixture = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../scripts/samples/ptiff_interop_fixture.tif");
        let canonical = std::fs::canonicalize(&fixture)
            .unwrap_or_else(|_| panic!("fixture missing: {}", fixture.display()));

        let fields = open_path_fields(&canonical).expect("open_path_fields(fixture)");
        assert!(!fields.is_empty(), "expected ptiff.* fields from fixture");

        let get = |needle: &str| {
            fields
                .iter()
                .find(|(k, _)| k == needle)
                .map(|(_, v)| v.as_str())
        };

        // Camera intrinsics that feed the 3x3 K matrix in Requirement 2/3.
        assert_eq!(get("ptiff.camera.model"), Some("pinhole"));
        assert_eq!(get("ptiff.camera.focal_length_x"), Some("700.0"));
        assert_eq!(get("ptiff.camera.focal_length_y"), Some("700.0"));
        assert_eq!(get("ptiff.camera.principal_x"), Some("64.000000"));
        assert_eq!(get("ptiff.camera.principal_y"), Some("64.000000"));
        assert_eq!(get("ptiff.spice.frame"), Some("IAU_MOON"));
    }

    #[test]
    fn open_path_fields_missing_file_errors() {
        let path = std::env::temp_dir().join(format!(
            "ptiff_fields_does_not_exist_{}.tif",
            std::process::id()
        ));
        assert!(open_path_fields(&path).is_err());
    }

    #[test]
    fn open_path_camera_reads_structured_calibration_fixture() {
        // The interop fixture carries intrinsics (fx=700, fy=700, cx=64, cy=64)
        // but no extrinsics. The structured camera must surface the 3x3 K
        // matrix and an identity / zero-translation [R|t], with P = K * [R|t]
        // collapsing onto K.
        let fixture = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../scripts/samples/ptiff_interop_fixture.tif");
        let canonical = std::fs::canonicalize(&fixture)
            .unwrap_or_else(|_| panic!("fixture missing: {}", fixture.display()));

        let cam = open_path_camera(&canonical).expect("open_path_camera(fixture)");
        assert!(cam.has_intrinsics, "expected intrinsics in fixture");
        assert_eq!(cam.focal_length_x, 700.0);
        assert_eq!(cam.focal_length_y, 700.0);
        assert_eq!(cam.principal_x, 64.0);
        assert_eq!(cam.principal_y, 64.0);
        // K = [ fx 0 cx ; 0 fy cy ; 0 0 1 ]
        assert_eq!(cam.intrinsics[0], 700.0);
        assert_eq!(cam.intrinsics[4], 700.0);
        assert_eq!(cam.intrinsics[2], 64.0);
        assert_eq!(cam.intrinsics[5], 64.0);
        assert_eq!(cam.intrinsics[8], 1.0);
        // No extrinsics fields in the fixture.
        assert!(
            !cam.has_extrinsics,
            "fixture should not advertise extrinsics"
        );
        // [R|t] is identity rotation, zero translation.
        assert_eq!(cam.extrinsics[0], 1.0);
        assert_eq!(cam.extrinsics[5], 1.0);
        assert_eq!(cam.extrinsics[10], 1.0);
        assert_eq!(cam.extrinsics[3], 0.0);
        // P first row = fx, 0, cx and bottom-right = 1.
        assert_eq!(cam.projection[0], 700.0);
        assert_eq!(cam.projection[2], 64.0);
        assert_eq!(cam.projection[10], 1.0);
    }

    #[test]
    fn open_path_camera_missing_file_errors() {
        let path = std::env::temp_dir().join(format!(
            "ptiff_camera_does_not_exist_{}.tif",
            std::process::id()
        ));
        assert!(open_path_camera(&path).is_err());
    }

    #[test]
    fn sink_create_with_camera_roundtrips_metadata() {
        // Write a tiled image whose `ptiff.camera.*` metadata carries full
        // intrinsics + extrinsics, then read it back and verify both the
        // scalar fields and the derived projection P = K * [R | t].
        let path = temp_tiff("camera_write");
        let builder = ImageDescriptorBuilder::new(32, 32, PixelType::UInt8).tile(16, 16);
        let cam = Camera::pinhole(
            700.0,
            715.0,
            32.0,
            24.0,
            1.0,
            0.0,
            0.0,
            0.0,
            1.0,
            2.0,
            3.0,
            Some("2026-08-21T12:34:56.000Z".to_string()),
        );

        {
            let sink = Sink::create_with_camera(&path, builder, &cam).expect("create camera sink");
            let tile = vec![0u8; sink.tile_byte_size()];
            for c in 0..2 {
                for r in 0..2 {
                    sink.write_tile(c, r, &tile).expect("write tile");
                }
            }
            // dropped here -> ptiff_sink_close flushes the writer.
        }

        assert!(path.exists(), "expected written file {}", path.display());

        let read = open_path_camera(&path).expect("open_path_camera");
        assert!(read.has_intrinsics);
        assert_eq!(read.focal_length_x, 700.0);
        assert_eq!(read.focal_length_y, 715.0);
        assert_eq!(read.principal_x, 32.0);
        assert_eq!(read.principal_y, 24.0);
        assert!(read.has_extrinsics);
        assert_eq!(read.rotation_w, 1.0);
        assert_eq!(read.position_x, 1.0);
        assert_eq!(read.position_y, 2.0);
        assert_eq!(read.position_z, 3.0);
        assert_eq!(read.timestamp, "2026-08-21T12:34:56.000Z");
        // Identity rotation R=I, position t=(1,2,3): translation column of
        // P = K*[R|t] is K*t -> P[0,3]=fx*tx+cx*tz, P[1,7]=fy*ty+cy*tz, P[2,11]=tz.
        assert!(
            (read.projection[0] - 700.0).abs() < 1e-9,
            "P00 = fx, got {}",
            read.projection[0]
        );
        assert!(
            (read.projection[3] - (700.0 * 1.0 + 32.0 * 3.0)).abs() < 1e-9,
            "P03 = fx*tx + cx*tz, got {}",
            read.projection[3]
        );
        assert!(
            (read.projection[7] - (715.0 * 2.0 + 24.0 * 3.0)).abs() < 1e-9,
            "P17 = fy*ty + cy*tz, got {}",
            read.projection[7]
        );
        assert!(
            (read.projection[11] - 3.0).abs() < 1e-9,
            "P211 = tz, got {}",
            read.projection[11]
        );

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn source_reads_back_sink_image() {
        // Write a 64x32 UInt8, 32x16-tiled image (2x2 = 4 tiles) with the
        // sink, then read all tiles back through the pixel-read Source API.
        let path = temp_tiff("source_roundtrip");
        let builder = ImageDescriptorBuilder::new(64, 32, PixelType::UInt8).tile(32, 16);

        let payload: Vec<u8> = (0..32 * 16).map(|i| i as u8).collect();
        {
            let sink = Sink::create(&path, builder).expect("create sink");
            for c in 0..2 {
                for r in 0..2 {
                    sink.write_tile(c, r, &payload).expect("write tile");
                }
            }
        } // drop(sink) -> flush

        let src = Source::open(&path).expect("open source");
        assert_eq!(src.tile_columns(), 2);
        assert_eq!(src.tile_rows(), 2);
        assert_eq!(src.tile_byte_size(), 32 * 16);

        let mut buf = vec![0u8; src.tile_byte_size()];
        for c in 0..2 {
            for r in 0..2 {
                let n = src.read_tile(c, r, &mut buf).expect("read tile");
                assert_eq!(n, payload.len());
                assert_eq!(&buf, &payload, "tile data must round-trip");
            }
        }

        // Converting the read descriptor to a builder reproduces the layout.
        let b = src.descriptor_builder().expect("descriptor_builder");
        assert_eq!(b.width, 64);
        assert_eq!(b.height, 32);
        assert_eq!(
            b.tile_info,
            Some(TileInfo {
                tile_width: 32,
                tile_height: 16
            })
        );

        // A too-small buffer is rejected with InvalidArgument (-1).
        let mut small = vec![0u8; src.tile_byte_size() - 1];
        assert_eq!(src.read_tile(0, 0, &mut small), Err(ReadError(-1)));
        // An out-of-grid index is OutOfRange (-2).
        let mut buf2 = vec![0u8; src.tile_byte_size()];
        assert_eq!(src.read_tile(9, 9, &mut buf2), Err(ReadError(-2)));

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn source_open_missing_file_errors() {
        let path = std::env::temp_dir().join(format!(
            "ptiff_source_does_not_exist_{}.tif",
            std::process::id()
        ));
        assert!(Source::open(&path).is_err());
    }

    #[test]
    fn pixel_type_has_friendly_names() {
        assert_eq!(PixelType::UInt8.name(), "UInt8");
        assert_eq!(PixelType::UInt16.name(), "UInt16");
        assert_eq!(PixelType::UInt32.name(), "UInt32");
        assert_eq!(PixelType::Float32.name(), "Float32");
        assert_eq!(PixelType::Float64.name(), "Float64");
    }

    #[test]
    fn camera_carries_model_by_default() {
        let cam = Camera::pinhole(
            700.0, 715.0, 32.0, 24.0, 1.0, 0.0, 0.0, 0.0, 1.0, 2.0, 3.0, None,
        );
        assert_eq!(cam.model, "pinhole");
    }

    #[test]
    fn camera_model_read_from_fields_fixture() {
        // The interop fixture stores `ptiff.camera.model == "pinhole"`, which
        // `open_path_camera` must surface on the idiomatic Camera struct even
        // though the C ABI struct has no model slot.
        let fixture = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../scripts/samples/ptiff_interop_fixture.tif");
        let canonical = std::fs::canonicalize(&fixture)
            .unwrap_or_else(|_| panic!("fixture missing: {}", fixture.display()));

        let cam = open_path_camera(&canonical).expect("open_path_camera(fixture)");
        assert_eq!(cam.model, "pinhole");
    }

    #[test]
    fn read_metadata_combines_file_fields_and_camera() {
        let fixture = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../scripts/samples/ptiff_interop_fixture.tif");
        let canonical = std::fs::canonicalize(&fixture)
            .unwrap_or_else(|_| panic!("fixture missing: {}", fixture.display()));

        let md = read_metadata(&canonical).expect("read_metadata(fixture)");
        assert_eq!(md.file.width, 128);
        assert_eq!(md.file.height, 128);
        assert_eq!(md.file.pixel_type, PixelType::UInt8);
        // The unified reader surfaces the extension fields and the camera.
        assert_eq!(md.field("ptiff.camera.model"), Some("pinhole"));
        assert_eq!(md.field("ptiff.spice.frame"), Some("IAU_MOON"));
        let cam = md.camera.expect("camera present");
        assert_eq!(cam.focal_length_x, 700.0);
    }

    #[test]
    fn read_metadata_plain_tiff_has_no_camera_or_fields() {
        // A plain (camera-less) tiled TIFF has an empty field list and no
        // camera; the unified reader must still succeed and report that.
        let path = temp_tiff("meta_plain");
        let builder = ImageDescriptorBuilder::new(16, 16, PixelType::UInt8).tile(16, 16);
        let sink = Sink::create(&path, builder).expect("create sink");
        sink.write_tile(0, 0, &vec![0u8; sink.tile_byte_size()])
            .expect("write tile");
        drop(sink);

        let md = read_metadata(&path).expect("read_metadata(plain)");
        assert_eq!(md.file.width, 16);
        assert!(
            md.fields.is_empty(),
            "expected no fields, got {:?}",
            md.fields
        );
        assert!(md.camera.is_none(), "expected no camera");
        assert_eq!(md.field("ptiff.camera.model"), None);

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn read_metadata_missing_file_errors() {
        let path = std::env::temp_dir().join(format!(
            "ptiff_metadata_does_not_exist_{}.tif",
            std::process::id()
        ));
        assert!(read_metadata(&path).is_err());
    }
}
