/*
 * ptiff_c_abiltest.c
 *
 * C ABI capability test over the PTIFF Rust core.
 *
 * Compiles against the cbindgen-GENERATED C header (target/ptiff_c.h, derived
 * from the Rust `extern "C"` surface in crates/ptiff-c — the source of truth)
 * and links against the ptiff-c staticlib (libptiff_c.a). It drives the real
 * Rust implementation over the C ABI and verifies values, so it proves the
 * Rust core is callable from pure C with no C++ anywhere in the picture.
 *
 * Coverage:
 *   - version ABI (struct-by-value + _out variants)
 *   - ptiff_error_code ordering
 *   - image bridge (create / accessors / destroy)
 *   - pixel bridge write->read round-trip (sink -> file -> source)
 *   - ptiff_open_path metadata on the written file
 *   - ptiff_backend_names / ptiff_free_string
 *   - logger surface (forwards to the core logger: set/level/log round-trip)
 *   - camera surface (ptiff_open_path_camera read + ptiff_sink_create_camera write
 *     round-trip through a real file)
 *
 * Build (see Makefile — run `make` in this directory):
 *   cc -I ../../../../target crates/ptiff-c/tests/c/ptiff_c_abiltest.c \
 *      -L target/release -lptiff_c -o abiltest && ./abiltest
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ptiff_c.h" /* generated by cbindgen from crates/ptiff-c (source of truth) */

static int failures = 0;

#define CHECK(cond, msg)                                                                           \
    do {                                                                                           \
        if (!(cond)) {                                                                             \
            fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, (msg));                        \
            failures++;                                                                            \
        }                                                                                          \
    } while (0)

/* The temporary file path we write and read back. */
static const char OUT_PATH[] = "./ptiff_c_abiltest_out.tif";

static void test_version(void) {
    ptiff_version ct = ptiff_compile_time_version();
    ptiff_version rt = ptiff_runtime_version();

    /* The workspace intends 1.0.0 as the release version. */
    CHECK(ct.major == 1, "compile-time major == 1");
    CHECK(ct.minor == 0, "compile-time minor == 0");
    CHECK(rt.major == ct.major && rt.minor == ct.minor && rt.patch == ct.patch,
            "runtime version equals compile-time");

    /* Out-param variants, including NULL-able pairs. */
    int m = -1, n = -1, p = -1;
    ptiff_runtime_version_out(&m, &n, &p);
    CHECK(m == 1 && n == 0 && p == 0, "runtime_version_out == 1.0.0");
    ptiff_compile_time_version_out(&m, &n, &p);
    CHECK(m == 1 && n == 0 && p == 0, "compile_time_version_out == 1.0.0");

    /* Either pointer may be NULL. */
    ptiff_runtime_version_out(NULL, NULL, NULL);
    ptiff_compile_time_version_out(NULL, NULL, NULL);
}

static void test_error_enum(void) {
    CHECK(PTIFF_ERROR_NOT_IMPLEMENTED == 0, "NOT_IMPLEMENTED==0");
    CHECK(PTIFF_ERROR_INVALID_ARGUMENT == 1, "INVALID_ARGUMENT==1");
    CHECK(PTIFF_ERROR_OUT_OF_RANGE == 2, "OUT_OF_RANGE==2");
    CHECK(PTIFF_ERROR_NOT_FOUND == 3, "NOT_FOUND==3");
    CHECK(PTIFF_ERROR_UNKNOWN == 4, "UNKNOWN==4");
}

static void test_image_bridge(void) {
    ptiff_image_descriptor d = {0};
    d.width = 40;
    d.height = 30;
    d.pixel_type = PTIFF_PIXEL_UINT16;
    d.channel_count = 3;
    d.has_gsd = 1;
    d.gsd = 1.25;
    d.has_compression = 1;
    d.compression = PTIFF_COMPRESSION_LZW;

    ptiff_image* img = ptiff_image_create(&d);
    CHECK(img != NULL, "image_create returns non-null");

    CHECK(ptiff_image_width(img) == 40, "image width == 40");
    CHECK(ptiff_image_height(img) == 30, "image height == 30");
    CHECK(ptiff_image_pixel_type(img) == PTIFF_PIXEL_UINT16, "pixel type uint16");
    CHECK(ptiff_image_channel_count(img) == 3, "channel count == 3");

    double gsd = 0.0;
    CHECK(ptiff_image_gsd(img, &gsd) == 1 && gsd == 1.25, "gsd present == 1.25");

    int comp = -1;
    CHECK(ptiff_image_compression(img, &comp) == 1 && comp == PTIFF_COMPRESSION_LZW,
            "compression present == LZW");

    /* tile_info is absent -> returns 0 and leaves out untouched */
    ptiff_tile_info ti = {0, 0};
    CHECK(ptiff_image_tile_info(img, &ti) == 0, "tile_info absent");
    CHECK(ti.tile_width == 0 && ti.tile_height == 0, "tile_info untouched");

    ptiff_image_destroy(img);
    ptiff_image_destroy(NULL); /* no-op */
}

static int write_roundtrip_file(void) {
    /* 34x34, UINT8, 1 channel, 16x16 tiles => 3x3 grid. */
    ptiff_image_descriptor d = {0};
    d.width = 34;
    d.height = 34;
    d.pixel_type = PTIFF_PIXEL_UINT8;
    d.channel_count = 1;
    d.has_tile_info = 1;
    d.tile_info.tile_width = 16;
    d.tile_info.tile_height = 16;

    ptiff_sink* sink = ptiff_sink_create(OUT_PATH, &d);
    if (sink == NULL) {
        CHECK(0, "sink_create non-null");
        return -1;
    }

    CHECK(ptiff_sink_tile_columns(sink) == 3, "sink columns == 3");
    CHECK(ptiff_sink_tile_rows(sink) == 3, "sink rows == 3");
    CHECK(ptiff_sink_tile_byte_size(sink) == 16 * 16, "sink tile bytes == 256");

    /* Each tile carries its row-major index+1 value (1..9). */
    const uint32_t cols = 3, rows = 3;
    uint8_t tile[16 * 16];
    for (uint32_t r = 0; r < rows; r++) {
        for (uint32_t c = 0; c < cols; c++) {
            memset(tile, r * cols + c + 1, sizeof(tile));
            int rc = ptiff_sink_write_tile(sink, c, r, tile, sizeof(tile));
            CHECK(rc == 0, "sink_write_tile ok");
        }
    }

    /* Negative paths: wrong size, out-of-grid, null sink. */
    memset(tile, 0, sizeof(tile));
    CHECK(ptiff_sink_write_tile(sink, 0, 0, tile, sizeof(tile) - 1) ==
                -PTIFF_ERROR_INVALID_ARGUMENT,
            "write with wrong size -> INVALID_ARGUMENT");
    CHECK(ptiff_sink_write_tile(sink, 99, 0, tile, sizeof(tile)) == -PTIFF_ERROR_OUT_OF_RANGE,
            "write out-of-grid -> OUT_OF_RANGE");
    CHECK(ptiff_sink_write_tile(NULL, 0, 0, tile, sizeof(tile)) == -PTIFF_ERROR_INVALID_ARGUMENT,
            "write null sink -> INVALID_ARGUMENT");

    ptiff_sink_close(sink);
    ptiff_sink_close(NULL); /* no-op */
    return 0;
}

static void test_pixel_bridge(void) {
    if (write_roundtrip_file() != 0)
        return;

    /* Read back via the source C ABI. */
    ptiff_source* src = ptiff_source_open(OUT_PATH, NULL);
    CHECK(src != NULL, "source_open non-null");
    if (src == NULL)
        return;

    ptiff_image_descriptor d = {0};
    CHECK(ptiff_source_descriptor(src, &d) == 0, "source_descriptor ok");
    CHECK(d.width == 34 && d.height == 34, "source dims 34x34");
    CHECK(d.pixel_type == PTIFF_PIXEL_UINT8, "source pixel type uint8");
    CHECK(d.channel_count == 1, "source channel count == 1");
    CHECK(d.has_tile_info == 1 && d.tile_info.tile_width == 16 && d.tile_info.tile_height == 16,
            "source tile info 16x16");

    const uint32_t cols = ptiff_source_tile_columns(src);
    const uint32_t rows = ptiff_source_tile_rows(src);
    const size_t tile_bytes = ptiff_source_tile_byte_size(src);
    CHECK(cols == 3 && rows == 3, "source grid 3x3");
    CHECK(tile_bytes == 16 * 16, "source tile bytes == 256");

    /* Verify each tile's content equals its expected index+1 value. */
    uint8_t buf[16 * 16];
    uint8_t exp[16 * 16];
    for (uint32_t r = 0; r < rows; r++) {
        for (uint32_t c = 0; c < cols; c++) {
            size_t bytes_read = 0;
            memset(buf, 0, sizeof(buf));
            int rc = ptiff_source_read_tile(src, c, r, buf, sizeof(buf), &bytes_read);
            CHECK(rc == 0, "source_read_tile ok");
            CHECK(bytes_read == tile_bytes, "bytes_read == tile bytes");
            memset(exp, r * cols + c + 1, sizeof(exp));
            CHECK(memcmp(buf, exp, sizeof(exp)) == 0, "tile content matches");
        }
    }

    /* Read with a too-small buffer -> INVALID_ARGUMENT. */
    size_t br = 0;
    CHECK(ptiff_source_read_tile(src, 0, 0, buf, sizeof(buf) - 1, &br) ==
                -PTIFF_ERROR_INVALID_ARGUMENT,
            "read with small buffer -> INVALID_ARGUMENT");

    ptiff_source_close(src);
    ptiff_source_close(NULL); /* no-op */
}

static void test_open_path(void) {
    ptiff_image_descriptor d = {0};
    int rc = ptiff_open_path(OUT_PATH, &d);
    CHECK(rc == 0, "open_path ok");
    CHECK(d.width == 34 && d.height == 34, "open_path dims 34x34");
    CHECK(d.pixel_type == PTIFF_PIXEL_UINT8, "open_path pixel type uint8");

    /* Missing file -> NOT_FOUND. */
    memset(&d, 0, sizeof(d));
    rc = ptiff_open_path("./does_not_exist_ptiff.tif", &d);
    CHECK(rc == -PTIFF_ERROR_NOT_FOUND, "open_path missing file -> NOT_FOUND");
}

static void test_backend_names(void) {
    char* names = ptiff_backend_names();
    CHECK(names != NULL, "backend_names non-null");
    if (names != NULL) {
        CHECK(strlen(names) > 0, "backend_names non-empty");
        /* The list is comma-separated; with only the TIFF backend ported so
         * far it is a single token, but it must contain no bare whitespace. */
        ptiff_free_string(names);
    }
    ptiff_free_string(NULL); /* no-op */
}

static void test_logger_and_camera(void) {
    /* Logger forwards to the core dependency-free logger: level is tracked and
     * reported (no longer a no-op stub). */
    ptiff_logger_set_level(PTIFF_LOG_DEBUG);
    CHECK(ptiff_logger_level() == PTIFF_LOG_DEBUG, "logger reports DEBUG");
    ptiff_logger_log(PTIFF_LOG_INFO, "hello from C"); /* callable, no panic */
    ptiff_logger_set_level(PTIFF_LOG_OFF);
    CHECK(ptiff_logger_level() == PTIFF_LOG_OFF, "logger reports OFF");
    ptiff_logger_set_level(PTIFF_LOG_INFO); /* reset for the rest of the test */

    /* Camera write path is implemented: sink_create_camera with a null camera
     * is rejected (INVALID_ARGUMENT -> NULL), matching ptiff_sink_create. */
    ptiff_image_descriptor d = {0};
    d.width = 34;
    d.height = 34;
    d.pixel_type = PTIFF_PIXEL_UINT8;
    d.channel_count = 1;
    d.has_tile_info = 1;
    d.tile_info.tile_width = 16;
    d.tile_info.tile_height = 16;
    ptiff_sink* s = ptiff_sink_create_camera(OUT_PATH, &d, NULL);
    CHECK(s == NULL, "sink_create_camera with null camera -> NULL");

    /* A complete camera round-trips through the file: write with camera, read
     * it back with ptiff_open_path_camera and verify the structured fields. */
    ptiff_camera cam;
    memset(&cam, 0, sizeof(cam));
    cam.has_intrinsics = 1;
    cam.focal_length_x = 900.0;
    cam.focal_length_y = 901.0;
    cam.principal_x = 512.5;
    cam.principal_y = 384.25;
    cam.intrinsics[0] = 900.0;
    cam.intrinsics[4] = 901.0;
    cam.intrinsics[2] = 512.5;
    cam.intrinsics[5] = 384.25;
    cam.intrinsics[8] = 1.0;
    cam.has_extrinsics = 1;
    cam.rotation_w = 0.7;
    cam.rotation_x = 0.1;
    cam.rotation_y = 0.2;
    cam.rotation_z = 0.3;
    cam.position_x = 1.0;
    cam.position_y = 2.0;
    cam.position_z = 3.0;

    s = ptiff_sink_create_camera(OUT_PATH, &d, &cam);
    CHECK(s != NULL, "sink_create_camera with camera -> non-null");
    if (s != NULL) {
        uint8_t tile[16 * 16];
        memset(tile, 5, sizeof(tile));
        for (uint32_t r = 0; r < 3; r++) {
            for (uint32_t c = 0; c < 3; c++) {
                CHECK(ptiff_sink_write_tile(s, c, r, tile, sizeof(tile)) == 0,
                        "camera sink write tile ok");
            }
        }
        ptiff_sink_close(s);
    }

    ptiff_camera readback;
    memset(&readback, 0, sizeof(readback));
    if (ptiff_open_path_camera(OUT_PATH, &readback) == 0) {
        CHECK(readback.has_intrinsics == 1, "readback has intrinsics");
        CHECK(readback.has_extrinsics == 1, "readback has extrinsics");
        CHECK(readback.focal_length_x == 900.0, "readback fx");
        CHECK(readback.principal_y == 384.25, "readback cy");
        CHECK(readback.rotation_w == 0.7, "readback rw");
        CHECK(readback.position_z == 3.0, "readback pz");
    } else {
        CHECK(0, "open_path_camera readback succeeds");
    }
}

int main(void) {
    printf("ptiff_c_abiltest: exercising the Rust core over the C ABI\n");

    test_version();
    test_error_enum();
    test_image_bridge();
    test_pixel_bridge();
    test_open_path();
    test_backend_names();
    test_logger_and_camera();

    if (failures) {
        fprintf(stderr, "ptiff_c_abiltest: %d FAILURE(S)\n", failures);
        return 1;
    }
    printf("ptiff_c_abiltest: ALL OK\n");
    return 0;
}
