/* Per-language buffer + out-parameter typemaps for the libptiff C ABI.

   The C ABI exposes tile buffers as counted (ptr, size) pairs and out-params
   as pointer args (int *err_out, uintptr_t *bytes_read). Each target language
   needs its OWN typemaps for these -- SWIG typemaps are language-specific and
   one language's typemaps do NOT apply to another (a Python Py_buffer typemap
   generated for Ruby would reference Python.h). So this file is guarded by the
   SWIG-provided per-language preprocessor macros.

   ACTIVE targets -- Go and Ruby are the two SWIG-backed languages (see the
   Makefile). Their blocks are selected by `SWIGGO` / `SWIGRUBY`, defined only
   when running `swig -go` / `swig -ruby`.

   INACTIVE -- `SWIGPYTHON` block below is kept as a historical reference only:
   Python is bound natively via PyO3 (crates/ptiff-python), so it is never
   built from SWIG. It is harmless dead code but documents the Write-buffer /
   Read-buffer / out-param / ptiff_field** / ptiff_camera* patterns clearly.

   ADDING ANOTHER LANGUAGE -- a new SWIG language (e.g. `swig -csharp`,
   `-java`, `-perl`, `-lua`, ...) is added by appending another `#elif defined(
   SWIG<LANG>)` branch. Each branch must map the same five C-ABI calling
   patterns the active branches cover (the grep audit in bindings/swig/README.md
   lists every function that uses them):
     1. (const uint8_t* buffer, uintptr_t buffer_size)  write tile  -- collapse
        onto one buffer/bytes argument; input length becomes buffer_size.
     2. (uint8_t* buffer, uintptr_t buffer_size)         read tile   -- map
        onto a writable buffer filled in place.
     3. *out pointer args (err_out, bytes_read, out, major/minor/patch) --
        surface as extra return values (OUTPUT pattern) or in/out refs.
     4. struct ptiff_field** out + int* out_count           (ptiff_open_path_fields)
        -- numinputs=0 in, walk array, copy to native list, ptiff_fields_free.
     5. struct ptiff_camera* out                            (ptiff_open_path_camera)
        -- numinputs=0 in, read scalars + K/[R|t]/P + timestamp into a native
        dict/object.
   Then add a matching `make <lang>` target in the Makefile (compile + link
   against libptiff_c via LIBC_* flags) following the ruby target's pattern.
   Use `-julia` only after confirming SWIG 4.x support; many runtimes are
   generated by `swig -lang`, e.g. `-perl5`, `-php7`, `-java`, `-csharp`.
*/

#ifdef SWIGPYTHON
/* Historical reference only -- Python is now PyO3 (crates/ptiff-python). */
/* ---- Python reference block (not built): buffers map onto Py_buffer. ---- */

/* Write side: (const uint8_t* buffer, uintptr_t buffer_size) collapses into one
   readable Python buffer; the input's length becomes buffer_size. */
%typemap(arginit) (const uint8_t* buffer, uintptr_t buffer_size) %{
  Py_buffer $1_buf;
%}
%typemap(in) (const uint8_t* buffer, uintptr_t buffer_size) %{
  if (PyObject_GetBuffer($input, &$1_buf, PyBUF_SIMPLE) < 0) {
    PyErr_SetString(PyExc_TypeError, "expected a bytes-like object");
    SWIG_fail;
  }
  $1 = (uint8_t *)$1_buf.buf;
  $2 = (uintptr_t)$1_buf.len;
%}
%typemap(freearg) (const uint8_t* buffer, uintptr_t buffer_size) %{
  PyBuffer_Release(&$1_buf);
%}

/* Read side: (uint8_t* buffer, uintptr_t buffer_size) -> one writable Python
   buffer (bytearray/memoryview); it is filled in place by the C function. */
%typemap(arginit) (uint8_t* buffer, uintptr_t buffer_size) %{
  Py_buffer $1_buf;
%}
%typemap(in) (uint8_t* buffer, uintptr_t buffer_size) %{
  if (PyObject_GetBuffer($input, &$1_buf, PyBUF_WRITABLE) < 0) {
    PyErr_SetString(PyExc_TypeError, "expected a writable bytes-like object (bytearray/memoryview)");
    SWIG_fail;
  }
  $1 = (uint8_t *)$1_buf.buf;
  $2 = (uintptr_t)$1_buf.len;
%}
%typemap(freearg) (uint8_t* buffer, uintptr_t buffer_size) %{
  PyBuffer_Release(&$1_buf);
%}

/* C ABI out-parameters surface as extra Python return values. Matched by
   (type, param name) pair, so this only touches the specific C ABI functions
   that declare a parameter with these exact names -- see the grep audit in
   the "alles in SWIG" migration notes (bindings/swig/README.md). */
%apply int *OUTPUT { int32_t *err_out };
%apply uintptr_t *OUTPUT { uintptr_t *bytes_read };
%apply double *OUTPUT { double *out };   /* ptiff_image_gsd */
%apply int *OUTPUT { int32_t *out };       /* ptiff_image_compression */
%apply int *OUTPUT { int32_t *major };       /* ptiff_{runtime,compile_time}_version_out */
%apply int *OUTPUT { int32_t *minor };
%apply int *OUTPUT { int32_t *patch };


/* ---- ptiff_open_path_fields(path, ptiff_field** out, int* out_count) ----
   Surfaces as `ptiff_open_path_fields(path)` returning a Python list of
   (key, value) string tuples. The two out-params are consumed inside the
   wrapper: `out` is filled in by the C function and `out_count` is its
   length; this typemap walks the resulting array, copies the strings into
   tuples, and frees the C array with ptiff_fields_free so the Python caller
   never sees raw pointers. The return code (0 == ok, negative == error) is
   kept as the leading return value. */
%typemap(in, numinputs=0) struct ptiff_field** out (ptiff_field* tmp) %{
  tmp = NULL;
  $1 = &tmp;
%}
%typemap(in, numinputs=0) int* out_count (int tmpcount) %{
  tmpcount = 0;
  $1 = &tmpcount;
%}
%typemap(argout) struct ptiff_field** out {
  /* arg2 == ptiff_field** out  (filled by the C function),
     arg3 == int* out_count (its length). */
  ptiff_field* farr = (arg2 != NULL) ? *arg2 : NULL;
  int n = (arg3 != NULL) ? *arg3 : 0;
  PyObject* lst = PyList_New(n > 0 ? n : 0);
  if (!lst) SWIG_fail;
  for (int i = 0; i < n; ++i) {
    PyObject* t = PyTuple_New(2);
    if (!t) { Py_DECREF(lst); SWIG_fail; }
    /* strings already null-terminated by ptiff_open_path_fields */
    PyTuple_SetItem(t, 0, SWIG_FromCharPtr(farr[i].key));
    PyTuple_SetItem(t, 1, SWIG_FromCharPtr(farr[i].value));
    PyList_SetItem(lst, i, t);
  }
  /* The signature of SWIG_Python_AppendOutput changed in SWIG 4.3.0
     (2024-06-15, commit #2907): pre-4.3 it is `(PyObject*, PyObject*)` (two
     args, no `is_void` flag); 4.3.0+ adds a third `int is_void`. Distro SWIG
     on the CI images we target (Ubuntu 24.04 -> 4.2.0, and older images ->
     4.0.x) is still pre-4.3, while the local/macOS toolchain is 4.5.0, so
     branch on SWIG_VERSION to stay buildable under both. We pass 0 (append,
     never free `lst`); the caller owns it. */
#if SWIG_VERSION >= 0x040300
  resultobj = SWIG_Python_AppendOutput(resultobj, lst, 0);
#else
  resultobj = SWIG_Python_AppendOutput(resultobj, lst);
#endif
  ptiff_fields_free(farr, n);
}

/* ---- ptiff_open_path_camera(path, ptiff_camera* out) ----
   Surfaces as `ptiff_open_path_camera(path)` returning a Python dict of the
   camera fields (scalars + K / [R|t] / P as flat lists of floats and the
   ISO-8601 timestamp string), plus the return code. The raw C struct is read
   back directly in the wrapper -- no pointer exposure. */
%typemap(in, numinputs=0) struct ptiff_camera* out (ptiff_camera cam_tmp) %{
  memset(&cam_tmp, 0, sizeof(cam_tmp));
  $1 = &cam_tmp;
%}
%typemap(argout) struct ptiff_camera* out {
  PyObject* d = PyDict_New();
  if (!d) SWIG_fail;
  PyDict_SetItemString(d, "has_intrinsics", PyLong_FromLong(cam_tmp2.has_intrinsics));
  PyDict_SetItemString(d, "has_extrinsics", PyLong_FromLong(cam_tmp2.has_extrinsics));
  PyDict_SetItemString(d, "focal_length_x", PyFloat_FromDouble(cam_tmp2.focal_length_x));
  PyDict_SetItemString(d, "focal_length_y", PyFloat_FromDouble(cam_tmp2.focal_length_y));
  PyDict_SetItemString(d, "principal_x", PyFloat_FromDouble(cam_tmp2.principal_x));
  PyDict_SetItemString(d, "principal_y", PyFloat_FromDouble(cam_tmp2.principal_y));
  PyDict_SetItemString(d, "rotation_w", PyFloat_FromDouble(cam_tmp2.rotation_w));
  PyDict_SetItemString(d, "rotation_x", PyFloat_FromDouble(cam_tmp2.rotation_x));
  PyDict_SetItemString(d, "rotation_y", PyFloat_FromDouble(cam_tmp2.rotation_y));
  PyDict_SetItemString(d, "rotation_z", PyFloat_FromDouble(cam_tmp2.rotation_z));
  PyDict_SetItemString(d, "position_x", PyFloat_FromDouble(cam_tmp2.position_x));
  PyDict_SetItemString(d, "position_y", PyFloat_FromDouble(cam_tmp2.position_y));
  PyDict_SetItemString(d, "position_z", PyFloat_FromDouble(cam_tmp2.position_z));
  {
    int i;
    PyObject* k = PyList_New(9);
    for (i = 0; i < 9; ++i) PyList_SET_ITEM(k, i, PyFloat_FromDouble(cam_tmp2.intrinsics[i]));
    PyDict_SetItemString(d, "intrinsics", k);
  }
  {
    int i;
    PyObject* e = PyList_New(12);
    for (i = 0; i < 12; ++i) PyList_SET_ITEM(e, i, PyFloat_FromDouble(cam_tmp2.extrinsics[i]));
    PyDict_SetItemString(d, "extrinsics", e);
  }
  {
    int i;
    PyObject* p = PyList_New(12);
    for (i = 0; i < 12; ++i) PyList_SET_ITEM(p, i, PyFloat_FromDouble(cam_tmp2.projection[i]));
    PyDict_SetItemString(d, "projection", p);
  }
  PyDict_SetItemString(d, "timestamp", PyUnicode_FromString((const char*)cam_tmp2.timestamp));
  /* Same SWIG_VERSION branch (>= 4.3.0) as the fields typemap above. */
#if SWIG_VERSION >= 0x040300
  resultobj = SWIG_Python_AppendOutput(resultobj, d, 0);
#else
  resultobj = SWIG_Python_AppendOutput(resultobj, d);
#endif
}


#elif defined(SWIGGO)
/* ---- Go: (ptr, size) buffer pairs collapse onto []byte. ---- */
/* Mirrors SWIG's own go/cdata.i pattern: the generated C wrapper extracts the
   slice's data pointer and length from the _goslice_ ($input.array/.len). */
%typemap(gotype) (const uint8_t* buffer, uintptr_t buffer_size) "[]byte"
%typemap(in) (const uint8_t* buffer, uintptr_t buffer_size) %{
  $1 = ($1_ltype)$input.array;
  $2 = ($2_ltype)$input.len;
%}
%typemap(gotype) (uint8_t* buffer, uintptr_t buffer_size) "[]byte"
%typemap(in) (uint8_t* buffer, uintptr_t buffer_size) %{
  $1 = ($1_ltype)$input.array;
  $2 = ($2_ltype)$input.len;
%}

/* err_out / bytes_read stay in/out *int / *int64 in Go -- the caller passes a
   pointer and reads the written value, matching Go's return-by-pointer idiom. */

#elif defined(SWIGRUBY)
/* ---- Ruby: (ptr, size) buffer pairs collapse onto a Ruby String. ---- */

%typemap(in) (const uint8_t* buffer, uintptr_t buffer_size) %{
  (void)StringValue($input);
  $1 = (uint8_t*)RSTRING_PTR($input);
  $2 = (uintptr_t)RSTRING_LEN($input);
%}

%typemap(in) (uint8_t* buffer, uintptr_t buffer_size) %{
  (void)StringValue($input);
  $1 = (uint8_t*)RSTRING_PTR($input);
  $2 = (uintptr_t)RSTRING_LEN($input);
%}

/* Ruby surfaces C out-params as extra return values via SWIG_Ruby_AppendOutput.
   Matched by (type, param name) pair -- see the grep audit in the "alles in
   SWIG" migration notes (bindings/swig/README.md). */
%apply int *OUTPUT { int32_t *err_out };
%apply uintptr_t *OUTPUT { uintptr_t *bytes_read };
%apply double *OUTPUT { double *out };   /* ptiff_image_gsd */
%apply int *OUTPUT { int32_t *out };       /* ptiff_image_compression */
%apply int *OUTPUT { int32_t *major };       /* ptiff_{runtime,compile_time}_version_out */
%apply int *OUTPUT { int32_t *minor };
%apply int *OUTPUT { int32_t *patch };

/* ---- ptiff_open_path_fields(path, ptiff_field** out, int* out_count) ----
   Surfaces as `Ptiff::ptiff_open_path_fields(path)` returning an Array of
   [key, value] string pairs (leading return code kept). Consumed the same
   way as the Python port: walk the C array, copy to Ruby strings, free. */
%typemap(in, numinputs=0) struct ptiff_field** out (ptiff_field* tmp) %{
  tmp = NULL;
  $1 = &tmp;
%}
%typemap(in, numinputs=0) int* out_count (int tmpcount) %{
  tmpcount = 0;
  $1 = &tmpcount;
%}
%typemap(argout) struct ptiff_field** out {
  ptiff_field* farr = (arg2 != NULL) ? *arg2 : NULL;
  int n = (arg3 != NULL) ? *arg3 : 0;
  VALUE arr = rb_ary_new();
  for (int i = 0; i < n; ++i) {
    VALUE pair = rb_ary_new();
    rb_ary_push(pair, rb_str_new2(farr[i].key));
    rb_ary_push(pair, rb_str_new2(farr[i].value));
    rb_ary_push(arr, pair);
  }
  /* SWIG_Ruby_AppendOutput gained a third `int is_void` in the same 4.3.0
     release as the Python form (2024-10-05, #2907); pre-4.3 distro SWIG
     (e.g. Ubuntu 24.04's 4.2.0) declares only `(VALUE, VALUE)`. Branch on
     SWIG_VERSION exactly like the Python typemaps above. We pass 0 (append;
     the caller owns `arr`, and fields are freed below). */
#if SWIG_VERSION >= 0x040300
  vresult = SWIG_Ruby_AppendOutput(vresult, arr, 0);
#else
  vresult = SWIG_Ruby_AppendOutput(vresult, arr);
#endif
  ptiff_fields_free(farr, n);
}

/* ---- ptiff_open_path_camera(path, ptiff_camera* out) ----
   Surfaces as `Ptiff::ptiff_open_path_camera(path)` returning a Ruby Hash of
   the camera fields (scalars + K / [R|t] / P as Arrays of floats and the
   ISO-8601 timestamp string), plus the return code. The populated struct is
   copied into fresh Ruby values, so no dangling pointer escapes the C frame. */
%typemap(in, numinputs=0) struct ptiff_camera* out (ptiff_camera cam_tmp) %{
  memset(&cam_tmp, 0, sizeof(cam_tmp));
  $1 = &cam_tmp;
%}
%typemap(argout) struct ptiff_camera* out {
  VALUE h = rb_hash_new();
  rb_hash_aset(h, rb_str_new2("has_intrinsics"), INT2NUM(cam_tmp2.has_intrinsics));
  rb_hash_aset(h, rb_str_new2("has_extrinsics"), INT2NUM(cam_tmp2.has_extrinsics));
  rb_hash_aset(h, rb_str_new2("focal_length_x"), DBL2NUM(cam_tmp2.focal_length_x));
  rb_hash_aset(h, rb_str_new2("focal_length_y"), DBL2NUM(cam_tmp2.focal_length_y));
  rb_hash_aset(h, rb_str_new2("principal_x"), DBL2NUM(cam_tmp2.principal_x));
  rb_hash_aset(h, rb_str_new2("principal_y"), DBL2NUM(cam_tmp2.principal_y));
  rb_hash_aset(h, rb_str_new2("rotation_w"), DBL2NUM(cam_tmp2.rotation_w));
  rb_hash_aset(h, rb_str_new2("rotation_x"), DBL2NUM(cam_tmp2.rotation_x));
  rb_hash_aset(h, rb_str_new2("rotation_y"), DBL2NUM(cam_tmp2.rotation_y));
  rb_hash_aset(h, rb_str_new2("rotation_z"), DBL2NUM(cam_tmp2.rotation_z));
  rb_hash_aset(h, rb_str_new2("position_x"), DBL2NUM(cam_tmp2.position_x));
  rb_hash_aset(h, rb_str_new2("position_y"), DBL2NUM(cam_tmp2.position_y));
  rb_hash_aset(h, rb_str_new2("position_z"), DBL2NUM(cam_tmp2.position_z));
  {
    VALUE k = rb_ary_new();
    for (int i = 0; i < 9; ++i) rb_ary_push(k, DBL2NUM(cam_tmp2.intrinsics[i]));
    rb_hash_aset(h, rb_str_new2("intrinsics"), k);
  }
  {
    VALUE e = rb_ary_new();
    for (int i = 0; i < 12; ++i) rb_ary_push(e, DBL2NUM(cam_tmp2.extrinsics[i]));
    rb_hash_aset(h, rb_str_new2("extrinsics"), e);
  }
  {
    VALUE p = rb_ary_new();
    for (int i = 0; i < 12; ++i) rb_ary_push(p, DBL2NUM(cam_tmp2.projection[i]));
    rb_hash_aset(h, rb_str_new2("projection"), p);
  }
  rb_hash_aset(h, rb_str_new2("timestamp"), rb_str_new2((const char*)cam_tmp2.timestamp));
  /* Lens (distortion) model: kind string + named parameter hash. */
  rb_hash_aset(h, rb_str_new2("has_lens"), INT2NUM(cam_tmp2.has_lens));
  rb_hash_aset(h, rb_str_new2("lens_kind"), rb_str_new2((const char*)cam_tmp2.lens_kind));
  {
    VALUE lp = rb_hash_new();
    for (uint32_t i = 0; i < cam_tmp2.lens_param_count && i < 8; ++i) {
      if (cam_tmp2.lens_param_key[i][0] != 0) {
        rb_hash_aset(lp, rb_str_new2((const char*)cam_tmp2.lens_param_key[i]),
                     DBL2NUM(cam_tmp2.lens_param_value[i]));
      }
    }
    rb_hash_aset(h, rb_str_new2("lens_parameters"), lp);
  }
  /* Same SWIG_VERSION branch (>= 4.3.0) as the fields typemap. */
#if SWIG_VERSION >= 0x040300
  vresult = SWIG_Ruby_AppendOutput(vresult, h, 0);
#else
  vresult = SWIG_Ruby_AppendOutput(vresult, h);
#endif
}

#endif
