# frozen_string_literal: true

module PTiff
  # Version of the Ruby binding gem (mirrors libptiff's 1.0.0).
  #
  # Hand-authored gem-metadata only -- ptiff.gemspec requires this file
  # directly, independent of lib/ptiff.bundle (promoted SWIG output,
  # regenerated by `make -C ../swig ruby`; see bindings/swig/README.md ->
  # "Planned migration").
  VERSION = "1.0.0"
end
