#!/usr/bin/env python3
"""Roundtrip test for the SWIG-generated ptiff module.

Writes a tiled TIFF through the ptiff_sink_* (write) surface, then reads it back
through ptiff_source_* (read) -- both generated by SWIG from the real C ABI
headers (bindings/swig/ptiff.i). Verifies the pixel data round-trips exactly and
that the image descriptor reads back as written.

Run `make test` in bindings/swig/ (or after a manual `make`) to build the module
and execute this.
"""

import os
import sys

import ptiff

OUT = os.path.join(os.path.dirname(__file__), "roundtrip_python.tif")


def main() -> int:
    # ---- Build the image descriptor from the SWIG-generated class ----
    desc = ptiff.ptiff_image_descriptor()
    desc.width = 32
    desc.height = 32
    desc.pixel_type = 0  # PTIFF_PIXEL_UINT8
    desc.channel_count = 1
    desc.has_tile_info = 1
    desc.tile_info.tile_width = 16
    desc.tile_info.tile_height = 16
    desc.has_compression = 0

    # ---- Write side (ptiff_sink_*) ----
    if os.path.exists(OUT):
        os.remove(OUT)
    sink = ptiff.ptiff_sink_create(OUT, desc)
    assert sink, "ptiff_sink_create returned NULL"

    cols = ptiff.ptiff_sink_tile_columns(sink)
    rows = ptiff.ptiff_sink_tile_rows(sink)
    bs = ptiff.ptiff_sink_tile_byte_size(sink)
    print(f"sink tile grid {cols}x{rows}, byte_size={bs}")
    assert (cols, rows) == (2, 2), (cols, rows)
    assert bs == 16 * 16, bs

    for c in range(cols):
        for r in range(rows):
            # distinct solid fill per tile
            pattern = bytes([(c * rows + r) % 256]) * bs
            ptiff.ptiff_sink_write_tile(sink, c, r, pattern)

    ptiff.ptiff_sink_close(sink)
    assert os.path.exists(OUT), "no file written"
    print("written", OUT, "size:", os.path.getsize(OUT))

    # ---- Read side (ptiff_source_*) ----
    # err_out is an int* OUTPUT -> surfaced as a second return value. It is only
    # meaningful on failure (uninitialized on success), so we only assert the handle.
    res = ptiff.ptiff_source_open(OUT)
    src = res[0] if isinstance(res, list | tuple) else res
    print("  src:", src)
    assert src, "ptiff_source_open returned NULL"

    d = ptiff.ptiff_image_descriptor()
    rc = ptiff.ptiff_source_descriptor(src, d)
    assert rc == 0, rc
    print(
        f"read-back descriptor: {d.width}x{d.height} px={d.pixel_type} "
        f"ch={d.channel_count} "
        f"tile={d.tile_info.tile_width}x{d.tile_info.tile_height} "
        f"comp={d.compression}"
    )
    assert (d.width, d.height) == (32, 32)
    assert (d.tile_info.tile_width, d.tile_info.tile_height) == (16, 16)

    rcols = ptiff.ptiff_source_tile_columns(src)
    rrows = ptiff.ptiff_source_tile_rows(src)
    rbs = ptiff.ptiff_source_tile_byte_size(src)
    print(f"source tile grid {rcols}x{rrows}, byte_size={rbs}")
    assert (rcols, rrows) == (2, 2)

    # read tile (1,0) back into a writable bytearray; buffer+size collapse to one arg
    buf = bytearray(rbs)
    res2 = ptiff.ptiff_source_read_tile(src, 1, 0, buf)
    print("read_tile(1,0) result:", res2)
    expected = bytes([(1 * rows + 0) % 256]) * rbs
    assert bytes(buf) == expected, "read-back tile (1,0) mismatch"

    ptiff.ptiff_source_close(src)

    print("ROUNDTRIP OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
